// <auto-generated />
namespace Web2ProjekatBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Opremachange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Opremachange));
        
        string IMigrationMetadata.Id
        {
            get { return "202106201741435_Oprema change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
