// <auto-generated />
namespace Web2ProjekatBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReturnResolution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReturnResolution));
        
        string IMigrationMetadata.Id
        {
            get { return "202106251109327_ReturnResolution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
